// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xaero.Models;

#nullable disable

namespace Xaero.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20241126141001_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xaero.Models.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Distribution");
                });

            modelBuilder.Entity("Xaero.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionCompanyId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("Xaero.Models.MovieDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("Money");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("MovieDetail");
                });

            modelBuilder.Entity("Xaero.Models.MovieDistribution", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("DistributionId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "DistributionId");

                    b.HasIndex("DistributionId");

                    b.ToTable("MovieDistribution");
                });

            modelBuilder.Entity("Xaero.Models.ProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("Money");

                    b.Property<DateTime>("EstablishmentDate")
                        .HasColumnType("Date");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductionCompany");
                });

            modelBuilder.Entity("Xaero.Models.Movie", b =>
                {
                    b.HasOne("Xaero.Models.ProductionCompany", "ProductionCompany_R")
                        .WithMany("Movie_R")
                        .HasForeignKey("ProductionCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionCompany_R");
                });

            modelBuilder.Entity("Xaero.Models.MovieDetail", b =>
                {
                    b.HasOne("Xaero.Models.Movie", "Movie_R")
                        .WithOne("MovieDetail_R")
                        .HasForeignKey("Xaero.Models.MovieDetail", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie_R");
                });

            modelBuilder.Entity("Xaero.Models.MovieDistribution", b =>
                {
                    b.HasOne("Xaero.Models.Distribution", "Distribution_R")
                        .WithMany("MovieDistribution_R")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xaero.Models.Movie", "Movie_R")
                        .WithMany("MovieDistribution_R")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution_R");

                    b.Navigation("Movie_R");
                });

            modelBuilder.Entity("Xaero.Models.Distribution", b =>
                {
                    b.Navigation("MovieDistribution_R");
                });

            modelBuilder.Entity("Xaero.Models.Movie", b =>
                {
                    b.Navigation("MovieDetail_R");

                    b.Navigation("MovieDistribution_R");
                });

            modelBuilder.Entity("Xaero.Models.ProductionCompany", b =>
                {
                    b.Navigation("Movie_R");
                });
#pragma warning restore 612, 618
        }
    }
}
